### PR TITLE
Use AppConfig so we support Django 1.9+

### PR DESCRIPTION
**Pull request by blag**

### CODE REVIEW

**Comment by blag** [comment]
This should help my other PRs (#8, #9, and #10) pass the Travis tests.

**Comment by blag** [comment]
Closing and reopening PR so Travis runs again.

**Comment by blag** [comment]
Whelp, I don't know why only Python 3.3/Django 1.9 and Python 3.3/Django master are failing, but the rest of them are passing.

Anyway, sorry for all of the noise. Once this is merged I'll rerun the Travis tests for my other PRs. Thanks for all of your work!

**Comment by MarkusH** [comment]
Thanks for the patch. Could you update the test matrix (travis and tox) to follow https://github.com/MarkusH/django-dynamic-forms :smile_cat: 

Also, mind squashing the commits into a single one.

**Comment by blag** [comment]
Done.

**Comment by MarkusH** [comment]
Thanks for your work. Merged in 29ea0781d47fdb05aa6ba514351306c8bbc391d6 :cookie: :apple:

**Pull request closed without merging**
