### PR TITLE
feat: support Django 1.11, 2.2 and 3.0

### PR DESCRIPTION
**Pull request by galuszkak**
Hi @MarkusH ,

Thanks for creating this package and contributing this package to python community. Really appreciate that!

I know you aren't supporting this package anymore but we are still using it (see here: https://oswiecimdziejesie.pl/wydarzenie/4508/ ) and it is really good package for someone who doesn't have access to any GeoDjango features like PostGIS.

Therefore I would like to ask, would you be willing to maybe give us (people from Hackerspace Silesia or me) permissions to release new packages and merging rights (or transfer repository to us?).

Here is our contribution with support for only Python 3 and Django 1.11 and 2.2 and 3.0

Thanks!

### CODE REVIEW

**Comment by netAction** [comment]
I don't know what to do here as I am no Django developer.
@saschan? @MarkusH? Could you help?

**Comment by MarkusH** [comment]
Hi @galuszkak. Thank you for your offer. I'll think about how to proceed.

**Comment by galuszkak** [comment]
Hi @MarkusH ,

Thank you for taking this into consideration. Appreciated that! Let me know how you would want to move forward.

**Comment by MarkusH** [comment]
Hi @galuszkak. Thanks for bearing with me. There are thre options, from my perspective:

1. You use your own fork and own PyPI package.
2. You use your own fork and I hand over the PyPI namespace to you.
3. We get the package into a state that it can be moved to @jazzband.

**Comment by galuszkak** [comment]
@MarkusH I'm fine with moving to @jazzband . My understanding that when this happens we have all things automated and anyone who is interested can maintain that, which is think best for community, not only me :) .

**Comment by galuszkak** [comment]
Hi @MarkusH,

Is there anything that I can do to help with that transition?

Thanks!

**Comment by MarkusH** [comment]
Merged with #19

**Comment by MarkusH** [comment]
Since Django 1.11 is out of support, I dropped (official) support for that.

**Comment by MarkusH** [comment]
And version 0.4.0 is out.

**Comment by galuszkak** [comment]
@MarkusH when I did PR, it was still in support as it support expired in 1st of April 2020 ;)

**Comment by MarkusH** [comment]
Yes, it was, indeed.

**Pull request closed without merging**
